### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [Open-Source-Chandigarh/sadakAI#1]
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add hacktoberfest labels.

**Comment by bakayu** [comment]
Please do!

**Comment by KiranBaliga** [comment]
@bakayu I have raised a PR based on the requirement. Please add required labels on the PR. Your feedback is highly appreciated. Thank you.

**Comment by bakayu** [comment]
Thank you for your contribution @KiranBaliga ,
Your efforts are much appreciated!
